export default [
    { id: "29ENMAdmNy0byJdF21AhGa", url: "https://open.spotify.com/track/29ENMAdmNy0byJdF21AhGa", title: "Watermelon", length: 198226, explicit: true },
    { id: "6FEDEeBd8E5T1TmBfMlys0", url: "https://open.spotify.com/track/6FEDEeBd8E5T1TmBfMlys0", title: "SEND THE RAIN (TO EVERYONE)", length: 322101, explicit: false },
    { id: "279Iabhr2afcc93hAc1YZ8", url: "https://open.spotify.com/track/279Iabhr2afcc93hAc1YZ8", title: "Black Dog", length: 82026, explicit: false },
    { id: "65D1Gw34nZZpjfcZPmOBwY", url: "https://open.spotify.com/track/65D1Gw34nZZpjfcZPmOBwY", title: "Oh My Stars", length: 302120, explicit: false },
    { id: "1MQwg2JTIHjdsOHUR6bdso", url: "https://open.spotify.com/track/1MQwg2JTIHjdsOHUR6bdso", title: "I Need To Know", length: 214280, explicit: false },
    { id: "14bJJQStOzZpcCxlAr4NOz", url: "https://open.spotify.com/track/14bJJQStOzZpcCxlAr4NOz", title: "Safe & Sound", length: 178329, explicit: false },
    { id: "4c1Lc5RsgYURf7hZlt4sR0", url: "https://open.spotify.com/track/4c1Lc5RsgYURf7hZlt4sR0", title: "That Kind Of Beautiful", length: 185190, explicit: false },
    { id: "2poCGYnBEGRXQ4q9F889CS", url: "https://open.spotify.com/track/2poCGYnBEGRXQ4q9F889CS", title: "Darlin'", length: 233520, explicit: false },
    { id: "56twDecxsQon61crfEXrA5", url: "https://open.spotify.com/track/56twDecxsQon61crfEXrA5", title: "Hollywood's Bleeding", length: 217777, explicit: false },
    { id: "75Vc1ge16jlwRmEGCqCc6l", url: "https://open.spotify.com/track/75Vc1ge16jlwRmEGCqCc6l", title: "Oh, Carolina", length: 205666, explicit: false },
    { id: "0tozhA4AZE7kDEvlcxCzP1", url: "https://open.spotify.com/track/0tozhA4AZE7kDEvlcxCzP1", title: "Undertow", length: 282453, explicit: false },
    { id: "7KyzYTcqtptWqlmEZAVPZV", url: "https://open.spotify.com/track/7KyzYTcqtptWqlmEZAVPZV", title: "From Here to Utopia", length: 354000, explicit: true },
    { id: "7Jt2m2zXpCkAdmUIfsIaWZ", url: "https://open.spotify.com/track/7Jt2m2zXpCkAdmUIfsIaWZ", title: "Whiskey in the Jar", length: 267653, explicit: false },
    { id: "3q7vmOvgX1DZIILnGRmAHM", url: "https://open.spotify.com/track/3q7vmOvgX1DZIILnGRmAHM", title: "Only the Wine", length: 172240, explicit: false },
    { id: "4fHJwyR7JILiSAbLyXcrKx", url: "https://open.spotify.com/track/4fHJwyR7JILiSAbLyXcrKx", title: "Don't Wanna Know - Acoustic Version", length: 183472, explicit: false },
    { id: "4UU97IGHOhBhZjCUgDFUiz", url: "https://open.spotify.com/track/4UU97IGHOhBhZjCUgDFUiz", title: "Sink Or Swim", length: 178093, explicit: false },
    { id: "30JxjencOWOx1F5m1FDvz6", url: "https://open.spotify.com/track/30JxjencOWOx1F5m1FDvz6", title: "Don't Keep Heaven Busy", length: 214153, explicit: false },
    { id: "1RIrP4WjP5k2yYDxWzCJdz", url: "https://open.spotify.com/track/1RIrP4WjP5k2yYDxWzCJdz", title: "Swelling Sea", length: 246164, explicit: false },
    { id: "3xQMRlwBgqvYWJX8TsOOgq", url: "https://open.spotify.com/track/3xQMRlwBgqvYWJX8TsOOgq", title: "Who Saved Who", length: 245840, explicit: false },
    { id: "5aAwAb26epRhjJvgoE1qCv", url: "https://open.spotify.com/track/5aAwAb26epRhjJvgoE1qCv", title: "Terrifyer", length: 148547, explicit: false },
    { id: "2vOFdBs2kss9U0ezRGTG2E", url: "https://open.spotify.com/track/2vOFdBs2kss9U0ezRGTG2E", title: "Remnants of What People Used to Be", length: 175046, explicit: true },
    { id: "12Dk1SYhyl5dmqb2BllDnD", url: "https://open.spotify.com/track/12Dk1SYhyl5dmqb2BllDnD", title: "Someone Like You // Acoustic", length: 221053, explicit: false },
    { id: "2DODPLqY24UuvUokVh2JwF", url: "https://open.spotify.com/track/2DODPLqY24UuvUokVh2JwF", title: "That's All I Need", length: 198466, explicit: false },
    { id: "4KgWwGrhtccvKkVq5LuY8a", url: "https://open.spotify.com/track/4KgWwGrhtccvKkVq5LuY8a", title: "Come Back Down", length: 228346, explicit: false },
    { id: "6Of87Sf8b20V1uj7VjeIvl", url: "https://open.spotify.com/track/6Of87Sf8b20V1uj7VjeIvl", title: "Let the Night", length: 238093, explicit: false },
    { id: "11qJo8BHxYDUg6NSVZp95i", url: "https://open.spotify.com/track/11qJo8BHxYDUg6NSVZp95i", title: "Girls Just Wanna Have Fun", length: 172992, explicit: false },
    { id: "2P8TddBcto4SMPB0G9dSAB", url: "https://open.spotify.com/track/2P8TddBcto4SMPB0G9dSAB", title: "Stealing", length: 257160, explicit: false },
    { id: "08oOVFb31KlJ8avWFTtHE0", url: "https://open.spotify.com/track/08oOVFb31KlJ8avWFTtHE0", title: "My Heart With You", length: 264240, explicit: false },
    { id: "0dJDvqSaf1kQEbUXbgsagt", url: "https://open.spotify.com/track/0dJDvqSaf1kQEbUXbgsagt", title: "Asking for a Friend", length: 235866, explicit: false },
    { id: "3CC3toUI04aaz6qH1OpjcI", url: "https://open.spotify.com/track/3CC3toUI04aaz6qH1OpjcI", title: "I Remember Her", length: 209539, explicit: false },
    { id: "4kp526fUmPUCdru1PAeNUV", url: "https://open.spotify.com/track/4kp526fUmPUCdru1PAeNUV", title: "鬼ヶ島", length: 154760, explicit: false },
    { id: "53T8DzkT63oDhUXSQJVul7", url: "https://open.spotify.com/track/53T8DzkT63oDhUXSQJVul7", title: "American Tune", length: 147120, explicit: false },
    { id: "2WaxBL2VVPUHqtfQE1yLbF", url: "https://open.spotify.com/track/2WaxBL2VVPUHqtfQE1yLbF", title: "Midnight Special - Remastered 2002", length: 185520, explicit: false },
    { id: "1bpCYUzfZTLdAknuel5Cnt", url: "https://open.spotify.com/track/1bpCYUzfZTLdAknuel5Cnt", title: "I Dream of You", length: 258056, explicit: false },
    { id: "1NxQeMVFB5VZ1vQEk4lNvd", url: "https://open.spotify.com/track/1NxQeMVFB5VZ1vQEk4lNvd", title: "Little Lies", length: 167706, explicit: false },
    { id: "0pvZsVZ95F6C6oSGTBCfLH", url: "https://open.spotify.com/track/0pvZsVZ95F6C6oSGTBCfLH", title: "El Camino", length: 242146, explicit: false },
    { id: "5KvvHQR3xGNZN7aq0CMjf6", url: "https://open.spotify.com/track/5KvvHQR3xGNZN7aq0CMjf6", title: "Come Home", length: 291833, explicit: false },
    { id: "0Pi3Ua6fJV1Yx5MGXhfybT", url: "https://open.spotify.com/track/0Pi3Ua6fJV1Yx5MGXhfybT", title: "Call You Mine (Acoustic Piano)", length: 209554, explicit: false },
    { id: "3ehaORXQ7WPWY62TU9tJct", url: "https://open.spotify.com/track/3ehaORXQ7WPWY62TU9tJct", title: "Cody's Theme", length: 123576, explicit: false },
    { id: "0Z2Q9i0qg8zKtK1rL5tFSu", url: "https://open.spotify.com/track/0Z2Q9i0qg8zKtK1rL5tFSu", title: "Blazing Highway Home", length: 298760, explicit: false },
    { id: "6nkiE9nZdyxQ6KtEb1uJq8", url: "https://open.spotify.com/track/6nkiE9nZdyxQ6KtEb1uJq8", title: "Details", length: 229224, explicit: false },
    { id: "7Jfj7U9W5Ws3k1Xh34RZ6W", url: "https://open.spotify.com/track/7Jfj7U9W5Ws3k1Xh34RZ6W", title: "Robin Williams", length: 181573, explicit: false },
    { id: "1WGMajtK2qQXuzGmAlRSTH", url: "https://open.spotify.com/track/1WGMajtK2qQXuzGmAlRSTH", title: "Nel Blu Dipinto Di Blu", length: 227238, explicit: false },
    { id: "6i6Wi5CAYZUFiQr4dP2QPm", url: "https://open.spotify.com/track/6i6Wi5CAYZUFiQr4dP2QPm", title: "To the Dogs or Whoever", length: 182946, explicit: false },
    { id: "6PbCEdjkgbUTDwyrJNn3Dm", url: "https://open.spotify.com/track/6PbCEdjkgbUTDwyrJNn3Dm", title: "The World Keeps Turnin'", length: 189026, explicit: false },
    { id: "1uejMUEJpPMmTA640NJXcu", url: "https://open.spotify.com/track/1uejMUEJpPMmTA640NJXcu", title: "Pilgrim", length: 235992, explicit: false },
    { id: "7C87cnbE6D7NiW0HHJlKn1", url: "https://open.spotify.com/track/7C87cnbE6D7NiW0HHJlKn1", title: "Lavender", length: 265760, explicit: false },
    { id: "5TJ025YL3gsi9c375RVmZy", url: "https://open.spotify.com/track/5TJ025YL3gsi9c375RVmZy", title: "Killing Me", length: 261320, explicit: false },
    { id: "6ogPBjEg8SeRrPQXpGQZvf", url: "https://open.spotify.com/track/6ogPBjEg8SeRrPQXpGQZvf", title: "Life Keeps Moving On", length: 196559, explicit: false },
    { id: "4hbGPfz03P8Nnh75mFIAoH", url: "https://open.spotify.com/track/4hbGPfz03P8Nnh75mFIAoH", title: "Lucky - Spotify Session", length: 391404, explicit: false }
]